# Gemini CLI用設定ファイル
project:
  name: "SEO Article Generator with Fact-Check"
  version: "2.1"
  description: "ファクトチェック強化版SEO最適化記事自動生成システム"

# コマンド設定
commands:
  article:
    description: "SEO記事を生成（ファクトチェック付き）"
    trigger_patterns:
      - "についての記事を作成"
      - "に関する記事"
      - "のSEO記事"
    execute: "INSTRUCTIONS_v2.md"  # WordPress完全対応版

# Gemini特有の設定
gemini_settings:
  model: "gemini-pro"
  temperature: 0.7
  max_output_tokens: 8000
  
  # 画像生成設定（Gemini CLIネイティブ機能）
  image_generation:
    enabled: true
    images_per_h2: 1
    style: "professional, clean, informative"
    save_to_output: true
    auto_optimize: true
  
# ツール設定
tools:
  web_search:
    enabled: true
    max_queries_per_phase: 25
  image_generation:
    enabled: true
    save_images: true
    optimize_for_web: true
    add_alt_text: true
  
# ファイル読み込み
context_files:
  - path: "INSTRUCTIONS.md"
    priority: "high"
  - path: "config/*.yaml"
    priority: "high"
  - path: "prompts/*.md"
    priority: "high"
  - path: "assets/wordpress.css"
    priority: "high"

# 出力設定
output:
  format: "html"
  save_to_file: true
  create_artifact: true
  create_directory: true
  directory_pattern: "output/{{date}}-{{title_slug}}"
  save_all_phases: true
  files:
    parsed_request: "00_parsed_request.json"
    research_data: "01_research_data.md"
    article_structure: "02_article_structure.md"
    draft: "03_draft.md"
    factchecked_draft: "03_5_factchecked_draft.md"
    factcheck_report: "03_5_factcheck_report.json"
    optimized_draft: "04_optimized_draft.html"
    image_metadata: "04_5_image_metadata.json"
    quality_report: "05_quality_report.json"
    final_output: "final.html"

# ワークフロー設定
workflow:
  enable_factcheck: true
  min_factcheck_score: 90
  min_quality_score: 85
  phases:
    - parse_request
    - research
    - structure
    - writing
    - factcheck
    - optimization
    - image_generation
    - finalization