# Prompt V2 Configuration - 柔軟なプロンプト戦略
name: "Prompt V2"
version: "2.0"
description: "Flexible prompt strategy for general article generation"

# プロンプト設定
prompts:
  directory: "Prompt_v2"
  encoding: "utf-8"
  
  # 各フェーズのプロンプトファイル
  files:
    phase1: "CHAT_01_phase1_analysis.md"
    phase2: "CHAT_02_structure_generation.md" 
    phase3: "CHAT_03_content_generation_v2.md"
    phase4: "CHAT_04_factcheck.md"
    phase5: "CHAT_05_seo_metadata.md"
    phase6: "CHAT_06_finalize.md"

# LLM設定
llm:
  provider: "anthropic"
  model: "claude-3-5-sonnet-20241022"
  default_temperature: 0.2
  max_tokens: 4000
  
  # フェーズ別設定
  phase_settings:
    phase1:
      temperature: 0.1
      structured_output: true
    phase2:
      temperature: 0.2
      structured_output: false
    phase3:
      temperature: 0.3
      structured_output: false
    phase4:
      temperature: 0.1
      structured_output: true
    phase5:
      temperature: 0.1
      structured_output: true
    phase6:
      temperature: 0.2
      structured_output: false

# 品質基準設定
quality:
  # 最低品質スコア
  minimum_scores:
    overall: 85
    factual_accuracy: 85
    regulatory_compliance: 90
    scientific_validity: 80
    
  # ファクトチェック設定
  factcheck:
    enabled: true
    required_sources: 3
    minimum_score: 85
    
  # SEO設定
  seo:
    keyword_density_range: [2.0, 4.0]  # 2-4%
    meta_description_length: [140, 160]
    title_length: [30, 32]

# 画像生成設定
images:
  enabled: true
  provider: "mcp_imagen"
  
  # 画像スタイル設定
  style:
    default: "clean, professional, Japanese aesthetic"
    article: "informative illustration for health/beauty blog"
    size: "1024x1024"
    format: "png"
    
  # 生成設定
  generation:
    max_images_per_article: 6
    timeout_seconds: 300
    retry_attempts: 3
    
  # 品質設定
  quality:
    minimum_success_rate: 0.8  # 80%以上の成功率

# 記事設定
article:
  # デフォルト設定
  defaults:
    word_count: 3200
    word_count_tolerance: 300  # ±300文字
    language: "ja"
    
  # 構造設定
  structure:
    min_sections: 4
    max_sections: 8
    require_faq: false  # v2は柔軟
    require_summary: true
    
  # HTML出力設定
  html:
    container_class: "article-content"
    semantic_markup: true
    accessibility: true
    
# 出力設定
output:
  # ファイル形式
  formats:
    - "json"
    - "html"
    - "md"
    
  # 保存設定
  save_intermediate: true  # 中間結果を保存
  save_raw_outputs: true   # 生出力も保存
  
  # ファイル命名
  naming:
    pattern: "{phase}_{timestamp}"
    timestamp_format: "%Y%m%d_%H%M%S"

# デバッグ・ログ設定
debug:
  enabled: false
  log_level: "INFO"
  save_prompts: true
  save_api_calls: true

# 外部連携設定
integrations:
  # Google Drive (オプション)
  google_drive:
    enabled: false
    folder_id: ""
    
  # リサーチ (オプション)
  research:
    enabled: false
    provider: "gemini"
    max_queries: 20
    
  # 通知 (オプション) 
  notifications:
    enabled: false
    slack_webhook: ""

# パフォーマンス設定
performance:
  # タイムアウト設定
  timeouts:
    phase_timeout: 600  # 10分
    total_timeout: 3600  # 60分
    
  # リトライ設定
  retry:
    max_attempts: 3
    backoff_factor: 2
    
  # 並列処理
  concurrency:
    enabled: false  # v2は順次処理
    max_workers: 1

# 検証設定
validation:
  # 入力検証
  input:
    strict_mode: false  # v2は柔軟
    required_fields:
      - "title"
      - "main_keywords"
      - "approach_target"
      - "eeat_elements"
      
  # 出力検証
  output:
    validate_json_schema: true
    validate_html_structure: true
    validate_word_count: true