# Prompt V3 Configuration - 厳密なテンプレート準拠戦略
name: "Prompt V3" 
version: "3.0"
description: "Strict template compliance strategy following ARTICLE-TEMPLATE-README.md"

# プロンプト設定
prompts:
  directory: "Prompt_v3"
  encoding: "utf-8"
  template_reference: "ARTICLE-TEMPLATE-README.md"
  
  # 各フェーズのプロンプトファイル
  files:
    phase1: "CHAT_01_phase1_analysis.md"
    phase2: "CHAT_02_structure_generation.md"
    phase3: "CHAT_03_content_generation_v3.md"  # v3専用
    phase4: "CHAT_04_factcheck.md"
    phase5: "CHAT_05_seo_metadata.md"
    phase6: "CHAT_06_finalize.md"

# LLM設定 - v3はより一貫性重視
llm:
  provider: "anthropic"
  model: "claude-3-5-sonnet-20241022"
  default_temperature: 0.1  # より低い温度で一貫性確保
  max_tokens: 4000
  
  # フェーズ別設定 - 全体的に低温度
  phase_settings:
    phase1:
      temperature: 0.05  # 最も厳密
      structured_output: true
    phase2:
      temperature: 0.1
      structured_output: false
    phase3:
      temperature: 0.2   # コンテンツ生成のみやや高め
      structured_output: false
    phase4:
      temperature: 0.05  # 厳密な検証
      structured_output: true
    phase5:
      temperature: 0.05  # 厳密なSEO
      structured_output: true
    phase6:
      temperature: 0.1   # 厳密な最終化
      structured_output: false

# 品質基準設定 - v3はより厳しい基準
quality:
  # 最低品質スコア (v2より高い)
  minimum_scores:
    overall: 90          # v2: 85
    factual_accuracy: 90 # v2: 85
    regulatory_compliance: 95  # v2: 90
    scientific_validity: 85   # v2: 80
    template_compliance: 90   # v3独自
    
  # ファクトチェック設定
  factcheck:
    enabled: true
    required_sources: 5    # v2: 3
    minimum_score: 90      # v2: 85
    template_compliance_check: true  # v3独自
    
  # SEO設定 - より厳密
  seo:
    keyword_density_range: [2.5, 3.5]  # v2: [2.0, 4.0] より狭い範囲
    meta_description_length: [145, 155] # v2: [140, 160] より狭い範囲
    title_length: [30, 32]  # 厳密に30-32文字
    template_seo_compliance: true  # v3独自

# 画像生成設定 - v3はより高品質
images:
  enabled: true
  provider: "mcp_imagen"
  
  # 画像スタイル設定 - より詳細
  style:
    default: "high-quality, clean, professional, Japanese aesthetic, template-compliant"
    article: "premium informative illustration for health/beauty blog, ARTICLE-TEMPLATE style"
    size: "1024x1024"
    format: "png"
    quality: "high"  # v3独自
    
  # 生成設定 - より厳密
  generation:
    max_images_per_article: 6
    timeout_seconds: 600   # v2: 300 より長い
    retry_attempts: 5      # v2: 3 より多い
    quality_check: true    # v3独自
    
  # 品質設定 - より高い基準
  quality:
    minimum_success_rate: 0.9  # v2: 0.8, 90%以上の成功率
    template_compliance_check: true  # v3独自

# 記事設定 - より厳密な要求
article:
  # デフォルト設定
  defaults:
    word_count: 3200
    word_count_tolerance: 200  # v2: 300, より厳密
    language: "ja"
    template_version: "v3"
    
  # 構造設定 - より厳しい要求
  structure:
    min_sections: 5        # v2: 4
    max_sections: 7        # v2: 8, より制限
    require_faq: true      # v2: false, v3は必須
    require_summary: true
    require_toc: true      # v3独自
    require_eeat_section: true  # v3独自
    
  # HTML出力設定 - より厳密
  html:
    container_class: "article-content"
    semantic_markup: true
    accessibility: true
    template_compliance: true  # v3独自
    validate_structure: true   # v3独自
    
# 出力設定 - より詳細な検証
output:
  # ファイル形式
  formats:
    - "json"
    - "html" 
    - "md"
    
  # 保存設定
  save_intermediate: true
  save_raw_outputs: true
  save_validation_reports: true  # v3独自
  
  # ファイル命名 - v3識別子付き
  naming:
    pattern: "{phase}_v3_{timestamp}"
    timestamp_format: "%Y%m%d_%H%M%S"
    include_version: true

# デバッグ・ログ設定 - より詳細
debug:
  enabled: false
  log_level: "INFO"
  save_prompts: true
  save_api_calls: true
  save_validation_details: true  # v3独自
  template_compliance_logging: true  # v3独自

# 外部連携設定
integrations:
  # Google Drive (オプション)
  google_drive:
    enabled: false
    folder_id: ""
    v3_folder_suffix: "_v3"  # v3独自
    
  # リサーチ (オプション)
  research:
    enabled: false
    provider: "gemini"
    max_queries: 25         # v2: 20, より多い
    quality_filter: true    # v3独自
    
  # 通知 (オプション)
  notifications:
    enabled: false
    slack_webhook: ""
    include_quality_metrics: true  # v3独自

# パフォーマンス設定 - より長いタイムアウト
performance:
  # タイムアウト設定
  timeouts:
    phase_timeout: 900   # v2: 600, 15分
    total_timeout: 5400  # v2: 3600, 90分
    
  # リトライ設定
  retry:
    max_attempts: 5      # v2: 3, より多い
    backoff_factor: 2
    
  # 並列処理 (v3は品質重視で順次処理)
  concurrency:
    enabled: false
    max_workers: 1

# 検証設定 - 非常に厳密
validation:
  # 入力検証
  input:
    strict_mode: true     # v2: false, v3は厳密
    required_fields:
      - "title"
      - "main_keywords"
      - "approach_target"
      - "eeat_elements"
    
    # v3独自の検証
    title_length_check: true
    keyword_format_check: true
    eeat_completeness_check: true
      
  # 出力検証 - 多層検証
  output:
    validate_json_schema: true
    validate_html_structure: true
    validate_word_count: true
    validate_template_compliance: true  # v3独自
    validate_seo_requirements: true     # v3独自
    validate_accessibility: true       # v3独自

# v3独自の高度な設定
advanced:
  # テンプレート準拠検証
  template_compliance:
    enabled: true
    reference_file: "ARTICLE-TEMPLATE-README.md"
    minimum_score: 90
    
  # 品質保証
  quality_assurance:
    enabled: true
    multi_stage_validation: true
    final_human_review_flag: true
    
  # メトリクス追跡
  metrics:
    track_compliance_scores: true
    track_quality_trends: true
    export_quality_reports: true