# ファクトチェックルール設定
factcheck:
  version: "1.0"
  
  # 信頼できる情報源の定義
  trusted_sources:
    government:
      - domain: "go.jp"
        trust_level: "very_high"
      - domain: "gov"
        trust_level: "very_high"
    academic:
      - domain: "ac.jp"
        trust_level: "high"
      - domain: "edu"
        trust_level: "high"
    medical:
      - keywords: ["医学会", "学会", "協会"]
        trust_level: "high"
    industry:
      - keywords: ["業界団体", "協会", "連合会"]
        trust_level: "medium_high"
  
  # 検証が必要な要素
  verification_required:
    - type: "statistics"
      description: "数値データ・統計情報"
      rules:
        - "出典の明記が必須"
        - "3年以内のデータを優先"
        - "複数ソースでの確認推奨"
    
    - type: "medical_claims"
      description: "健康・医療に関する主張"
      rules:
        - "医学的根拠が必須"
        - "誇大表現の禁止"
        - "薬機法への配慮"
    
    - type: "effectiveness"
      description: "効果・効能の記述"
      rules:
        - "客観的データの裏付け"
        - "個人差の明記"
        - "断定的表現の回避"
    
    - type: "comparisons"
      description: "他社・他製品との比較"
      rules:
        - "公正な比較"
        - "客観的基準の使用"
        - "誹謗中傷の禁止"
  
  # 使用を避けるべき表現
  prohibited_expressions:
    absolute:
      - "必ず"
      - "100%"
      - "絶対に"
      - "間違いなく"
    unverified:
      - "〜と言われています"
      - "〜らしいです"
      - "〜かもしれません"
      - "おそらく"
    exaggerated:
      - "最高の"
      - "日本一の"
      - "唯一の"
      - "革命的な"
  
  # 推奨される表現
  recommended_expressions:
    statistics: "〜によると"
    research: "〜の研究では"
    general: "一般的に"
    experience: "当店の経験では"
    customer: "お客様の声では"
  
  # ファクトチェックスコアリング
  scoring:
    source_reliability:
      very_high: 100
      high: 85
      medium_high: 70
      medium: 50
      low: 0
    
    verification_status:
      verified_multiple: 100
      verified_single: 80
      partially_verified: 50
      unverified: 0
    
    pass_threshold: 85