# SEO記事生成システム要件
requirements:
  version: "1.0"
  
  # 記事の基本要件
  article:
    min_word_count: 3000
    max_word_count: 5000
    target_audience: "店舗の見込み客"
    purpose: "集客・信頼構築"
    
  # SEO要件
  seo:
    title_length:
      min: 25
      max: 60
    meta_description_length:
      min: 120
      max: 160
    keyword_density:
      min: 1
      max: 3
    heading_structure:
      h1_count: 1
      h2_min: 3
      h3_recommended: true
      
  # コンテンツ品質要件
  quality:
    originality_score: 95  # %
    readability_level: "中学生レベル"
    fact_accuracy: 90  # %
    engagement_elements:
      - "具体例"
      - "統計データ"
      - "専門的知見"
      - "実用的アドバイス"
      
  # 技術要件
  technical:
    format: "HTML"
    encoding: "UTF-8"
    responsive: true
    wordpress_compatible: true
    
  # 画像要件
  images:
    generation_enabled: true
    format: "webp"
    dimensions:
      width: 800
      height: 600
    quality: 85
    max_filesize_kb: 200
    alt_text_length:
      min: 80
      max: 120
    seo_requirements:
      - "メインキーワードを含む"
      - "具体的で説明的"
      - "視覚的内容を正確に記述"
    per_article:
      min: 6
      max: 8
    
  # コンプライアンス要件
  compliance:
    copyright: "オリジナルコンテンツ必須"
    medical_disclaimer: "必要に応じて追加"
    data_accuracy: "最新かつ正確な情報"
    legal_check: "薬機法・景表法準拠"