workflow:
  name: "SEO記事自動生成ワークフロー（ファクトチェック強化版）"
  version: "2.1"
  
  phases:
    - id: "parse"
      name: "リクエスト解析"
      prompt: "prompts/00_parse_request.md"
      output: "parsed_request"
      
    - id: "research"
      name: "情報収集・競合分析"
      prompt: "prompts/01_research.md"
      requires: ["web_search"]
      min_searches: 15
      max_searches: 25
      focus: "trusted_sources"
      
    - id: "structure"
      name: "記事構成計画"
      prompt: "prompts/02_structure.md"
      
    - id: "writing"
      name: "本文執筆"
      prompt: "prompts/03_writing.md"
      
    - id: "factcheck"
      name: "ファクトチェック"
      prompt: "prompts/03_5_factcheck.md"
      requires: ["web_search"]
      min_searches: 5
      max_searches: 10
      validation_rules: "config/factcheck_rules.yaml"
      output:
        - "03_5_factchecked_draft.md"
        - "03_5_factcheck_report.json"
      
    - id: "optimization"
      name: "SEO/LLMO最適化"
      prompt: "prompts/04_optimization_v2.md"
      # CSSは完全にインラインで記述するため、外部アセット不要
      
    - id: "image_generation"
      name: "AI画像生成・最適化"
      prompt: "prompts/04_5_image_generation.md"
      settings:
        images_per_h2: 1
        generate_variations: 2
        auto_optimize: true
      output:
        - "04_5_generated_images.json"
        - "output/images/"
      
    - id: "finalization"
      name: "最終調整・品質保証"
      prompt: "prompts/05_finalization.md"
      quality_threshold: 85
      factual_accuracy_threshold: 90

  # ファクトチェック設定
  factcheck_settings:
    enabled: true
    strict_mode: true
    require_multiple_sources: true
    max_age_days: 1095  # 3年
    
  # 信頼性重視の設定
  reliability:
    priority: "highest"
    public_trust: "essential"
    legal_compliance: "required"