name: Article Generation V4 Test

on:
  workflow_dispatch:
    inputs:
      article_title:
        description: '記事タイトル'
        required: true
        type: string
        default: 'テスト記事'

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: GA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Test YAML validation
        run: |
          echo "✅ YAML validation successful"
          echo "Article title: ${{ inputs.article_title }}"